import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/./header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#f7f7f7] antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
